server.port: 8020

spring:
    datasource.url: jdbc:mysql://${CC_MYSQL_SERVER_VERIFICATION}/codelet_cloud_verification?useUnicode=true&characterEncoding=utf-8&useSSL=false

application.resources.captcha-fonts: ${CC_CAPTCHA_FONT_DIR}
